on: push

jobs:
  get-repo-info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      env:
        org: devops-actions
      with:
        script: |
          // load all repos from the org, with pagination
          const repos = await github.paginate(github.rest.repos.listForOrg, {org: process.env.org})

          // loop over the repos and print their topics from the topics array property
          for (const repo of repos) {
            const topics = repo.topics

            if (topics && topics.length > 0) {
              console.log(`${repo.name}: ${topics.join(', ')}`)
            }
            else {
              console.log(`${repo.name}: No topics`)
              console.log(`${repo.name}: ${topics}`)
            }

            if (repo.name === `load-available-actions`) {
              // dump the repo object to the console
              console.log(repo)  
            }
          }
