on: push

jobs:
  get-repo-info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      env:
        org: devops-actions
      with:
        script: |
          // load all repos from the org, with pagination
          const repos = await github.paginate(github.rest.repos.listForOrg, {org: process.env.org})

          // loop over the repos and print their topics from the topics array property
          // array to hold the name and count
          var foundTopics = []
          var reposWithOutTopics = 0
          for (const repo of repos) {
            const topics = repo.topics

            if (topics && topics.length > 0) {
              console.log(`${repo.name}: ${topics.join(', ')}`)

              // loop over the topics and add them to the array
              for (const topic of topics) {
                // check if the topic is already in the array
                const index = foundTopics.findIndex(t => t.name === topic)
                if (index === -1) {
                  // if not, add it
                  foundTopics.push({name: topic, count: 1})
                }
                else {
                  // if it is, increment the count
                  foundTopics[index].count++
                }
              }

            }
            else {
              console.log(`${repo.name}: No topics`)
              reposWithOutTopics++
            }
          }

          // sort the array by count
          const sorted = foundTopics.sort((a, b) => b.count - a.count)
          // show the counts
          console.log(sorted)
          console.log(`----------------------------`)
          console.log(`Repos without topics: ${reposWithOutTopics}`)
