on: push

jobs:
  get-repo-info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      env:
        org: devops-actions
      with:
        script: |
          // load all repos from the org, with pagination
          const repos = await github.paginate(github.rest.repos.listForOrg, {org: process.env.org})
          console.log(`Found ${repos.length} repos`)

          function updateTopic(newTopic, repo) {
            newTopic.count++
            switch (repo.visibliity) {
              case 'internal':
                newTopic.internal++
                break
              case 'private':
                newTopic.private++
                break
              case 'public':
                newTopic.public++
                break
            }

            return newTopic
          }

          // loop over the repos and print their topics from the topics array property
          // array to hold the name and count
          var foundTopics = []
          var reposWithOutTopics = 0
          for (const repo of repos) {
            const topics = repo.topics

            if (topics && topics.length > 0) {
              console.log(`${repo.name}: ${topics.join(', ')}`)

              // loop over the topics and add them to the array
              for (const topic of topics) {
                // check if the topic is already in the array
                const index = foundTopics.findIndex(t => t.name === topic)
                if (index === -1) {
                  // if not, add it
                  var newTopic = {name: topic, count: 0, internal:0, private: 0, public: 0}
                  newTopic = updateTopic(newTopic, repo)
                  foundTopics.push(newTopic)
                }
                else {
                  // if it is, increment the counts
                  updateTopic(foundTopics[index], repo)                  
                }
              }

            }
            else {
              console.log(`${repo.name}: No topics`)
              reposWithOutTopics++
            }
          }

          // sort the array by count
          const sorted = foundTopics.sort((a, b) => b.count - a.count)
          // show the counts
          console.log(sorted)
          console.log(`----------------------------`)
          console.log(`Repos without topics: ${reposWithOutTopics}`)
